### ISSUE TITLE
Creating new areas by editing the configuration.yaml has no effect

### ISSUE THREAD

**Issue by ontolo-zz** [jseidl/hass-magic_areas#10]
Having added magic_areas successfully, restart and observe that areas exist:

`magic_areas:
`

Now create (or edit) areas by editing the configuration.yaml, and restart.
```
magic_areas:
  the_new_or_existing_area:
     include_entities: 
       - binary_sensor.front_door
       - binary_sensor.entrance_motion
```

Nothing happens, after restart the_new_or_existing_area does not exist.

**Comment by ontolo-zz** [comment]
Or, in the case of an existing area, the entities mentioned in configuration.yaml are not added to the existing magic config

**Comment by jseidl** [comment]
Areas should be created on the area registry only. The configuration entry is only for configuring said area.

For existing areas, make sure the area slug is correct. You can verify this by checking the created sensor name. Please provide more information so I can help debug what's going on.

**Comment by ontolo-zz** [comment]
The magic sensor area_hallway has been magically created and I can see it in the developer tools, defined as:

```
binary_sensor.area_hallway

presence_sensors:
  - binary_sensor.entrance_motion
  - switch.area_presence_hold_hallway
```

I want a binary door sensor exposed via MQTT to be included in the magic area so in the configuration.yaml I have:

```
magic_areas:
  area_hallway:
     include_entities: 
       - binary_sensor.front_door
```

But the front door sensor is still not included in the sensor after a restart.

**Comment by jseidl** [comment]
Oh that's because `door` device class is not included by default. Check the `presence_sensor_device_class` documentation on Readme. You have to add this entry with all the device classes you want. This overrides the default so make sure you add them back too.

**Comment by jseidl** [comment]
Also the slug is without `area`. In your case would be just `hallway`

**Comment by ontolo-zz** [comment]
It works as you have described. Thank you for your help which resolved my problem.

```
magic_areas:
  hallway:
     presence_sensor_device_class:
       - door
       - motion    
     include_entities: 
       - binary_sensor.front_door
```
Now the hallway magic area contains both the magically discovered area sensors AND the added door sensor, this is correct.

```
binary_sensor.area_hallway

binary_sensor.entrance_motion, 
binary_sensor.front_door, 
switch.area_presence_hold_hallway
```
