### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#28]
I configured one of my areas very basically:

```
kuche:
    control_lights: true
    control_climate: false
    control_media: false
    automatic_lights:
      entities:
        - light.kuche_spule
```

The `binary_sensor.area_kuche` turns to on after walking in front of the motion sensor. 
![image](https://user-images.githubusercontent.com/18382402/97026049-2dd2e280-1559-11eb-9064-790b14911629.png)

But the light doesn't turn on. This happens on a other area as well. The logs don't provide any related errors.

Edit:

Added
`custom_components.magic_areas: debug`
to logger. Maybe I get more information about whats going on.

Edit 2:

What does this mean?
`2020-10-23 20:14:58 INFO (SyncWorker_11) [custom_components.magic_areas.binary_sensor] Küche is on passive mode.`
