### ISSUE TITLE
Light turns on when disable_entity is deactived

### ISSUE THREAD

**Issue by sti0** [jseidl/hass-magic_areas#50]
I have configured one area with a `disable_entity` and custom `disable_state `("off"). If the `disable_entity `turns to `off`, the light turns `off `(if `on`) and stays `off `even when the area is occupied. If the area is occupied and the `disable_entity `turns to `on `again (reverse logic), the lights turning `on` as expected.

But somehow I have the issue that the light turns automatically `on `if the `disable_entity `turns to `on `again and the area is NOT occupied. It seems that there's a check missing if the area is occupied when switching `disable_entity `to the desired state. As the area is not occupied and therefore won't get unoccupied the lights stay on all the time.

Config:
```
magic_areas:
  flur_unten:
    control_lights: true
    control_climate: false
    control_media: false
    include_entities:
      - binary_sensor.dsr_haustuer_contact
    presence_sensor_device_class:
      - motion
      - door
    automatic_lights:
      disable_entity: binary_sensor.area_flur_unten_active
      disable_state: "off"
    clear_timeout: 20
```
