### ISSUE TITLE
Windows are considered doors

### ISSUE THREAD

**Issue by syphernl** [jseidl/hass-magic_areas#53]
A window entity with `device_class: window` is being included in the `*_doors` groups.  No `*_windows` groups are being created.

```
HASS Version | 0.118.3
HASS Type | Home Assistant Core
Magic_Areas version | 1.1.0
```

**Comment by jseidl** [comment]
That shouldn't be happening. Can you post the attributes (from developer tools) of both the `area_door_*` and the device with `device_class: window` that is going into that aggregation?

**Comment by JakeHertenstein** [comment]
I've run into the same issue. I turned on debugging but no Window aggregates are created.
Attributes of my `binary_sensor.openclose_77` (a Sonoff DS01 contact switch over Deconz):
```
on: true
friendly_name: Bedroom Window
device_class: window
```

`binary_sensor.area_bedroom`:
```
presence_sensors: binary_sensor.bedroom_occupancy, binary_sensor.presence_25, binary_sensor.openclose_32, binary_sensor.openclose_34, binary_sensor.openclose_77, binary_sensor.withings_in_bed_jake, switch.area_presence_hold_bedroom
active_sensors: binary_sensor.openclose_32, binary_sensor.withings_in_bed_jake
lights: light.nightstands, light.dresser
climate: 
clear_timeout: 600
update_interval: 15
on_states: on, home, playing, open
exterior: false
automatic_lights: disabled
friendly_name: Area (Bedroom)
icon: mdi:texture-box
device_class: occupancy
```

Settings:
```
    bedroom:
      clear_timeout: 600
      control_lights: false
      control_climate: false
      include_entities:
        - binary_sensor.withings_in_bed_jake
      exclude_entities:
        - binary_sensor.master_bedroom_fan_occupancy
        - light.extended_color_light_41
        - light.extended_color_light_44
        - light.bedroom
```

Versions:
```
Home Assistant: 2021.1.1
Type: Supervised
magic_areas: v.1.1.2
```
