### ISSUE TITLE
Magic Areas will not load HA areas unless there's at least 1 room definition on YAML

### ISSUE THREAD

**Issue by ACrazyConcept** [jseidl/hass-magic_areas#57]
I wanted to try this, but HA never finishes starting up and just stops responding completely at some point mid startup.
I had only added `magic_areas:` to my config.
Nothing of relevance in the log except this:
`
2020-11-23 17:46:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for magic_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
`

Then the log also stops outputting anything.
I do have quite a few entities if that could have something to say.

**Comment by sti0** [comment]
Do you have specified areas in HA?

https://www.home-assistant.io/integrations/config/#areas

**Comment by ACrazyConcept** [comment]
@sti0 I do.
But tbh. I have no clue about what to do with them, other than trying magic areas.
![image](https://user-images.githubusercontent.com/36438756/100372429-7fafd200-3009-11eb-9d1f-b4e8c1269db7.png)

**Comment by jseidl** [comment]
The log message you see is normal, all custom_components (as far as I know) raise this warning. 

Can you search for `binary_sensor.area_*` on Developer Tools and see if you see anything?

**Comment by ACrazyConcept** [comment]
> 
> 
> The log message you see is normal, all custom_components (as far as I know) raise this warning.
> 
> Can you search for `binary_sensor.area_*` on Developer Tools and see if you see anything?

Sure thing. There are no binary_sensor.area_* entities.

**Comment by dvbit** [comment]
I second that. HA not starting for me. 
granted I have about100ds entities.
but it is hanging.
I see the log is not advancing

**Comment by dvbit** [comment]
and i can confirm it it realted to this component.
If I remove the configuration ha starts

**Comment by sti0** [comment]
Did you any further configuration or just added `magic_areas:` without configuration?

**Comment by dvbit** [comment]
just plain magic_areas to start

**Comment by sti0** [comment]
Could you try to add at least one area?

**Comment by dvbit** [comment]
I mean I have just that configuration for magic_areas.
I have all Homeassisant  areas defined.
However I will add some basic configuration to magic_areas and reboot

**Comment by dvbit** [comment]
adding details for at least one area made it boot

**Comment by dvbit** [comment]
nope ... keeps spinning the wheel

**Comment by dvbit** [comment]
I can confirm that adding at least details for one area seems to solve

**Comment by jseidl** [comment]
@dvbit did adding details for one area made the others pop too?

**Comment by dvbit** [comment]
Yes

**Comment by jseidl** [comment]
Thanks for the report, I believe we got to the root of the problem, will investigate and work in a fix. It should work with only the basic definition set.

**Comment by ACrazyConcept** [comment]
> 
> 
> Thanks for the report, I believe we got to the root of the problem, will investigate and work in a fix. The intended operation is that it should work with only the basic definition set.

That sounds good, and sorry for the late follow-up. Can confirm it starts up with:

```
magic_areas:
  living_room:
    include_entities:
      - light.living_room
```

**Comment by jseidl** [comment]
I just spined up a dev VM with single `magic_areas:` definition. All the built-in areas were captured and working fine without any further room declaration. Will close this. If anyone goes through this again we'll reopen.

Config:
```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.magic_areas: debug

magic_areas:
```

![image](https://user-images.githubusercontent.com/283041/105008090-a416a200-59ed-11eb-9456-699f4b359e98.png)
