### ISSUE TITLE
Problem: Can't for the life of me figure out how to configure this...

### ISSUE THREAD

**Issue by danielbrunt57** [jseidl/hass-magic_areas#65]
Invalid config for [magic_areas]: expected a dictionary for dictionary value @ data['magic_areas']['living_room']['automatic_lights']. Got ['light.fireplace_light']
extra keys not allowed @ data['magic_areas']['living_room']['disable_entity']. Got 'input_boolean.sleep_mode'. (See /config/configuration.yaml, line 128). 

configuration.yaml with my #commented entries:
```
magic_areas:
  bedroom:
    presence_sensor_device_class: ['motion']
    automatic_lights:
      disable_entity: input_boolean.sleep_mode
#    automatic_lights:
#      - light.bedroom_lights
#    include_entities:
#      - binary_sensor.lumi_sensor_motion_bedroom
  office:
    presence_sensor_device_class: ['motion']
#    automatic_lights:
#      - light.office_lights
#    include_entities:
#      - binary_sensor.motion_office
  living_room:
#    presence_sensor_device_class: ['motion']
    automatic_lights:
      - light.fireplace_light
    disable_entity: 'input_boolean.sleep_mode'
#      entities:
#        - switch.switchlinc_relay_dual_band_1f_b7_25
#    include_entities:
#      - binary_sensor.lumi_sensor_motion_living_room
#      - switch.switchlinc_relay_dual_band_1f_b3_c5
```
I seem to be able to specify the disable entity in automatic lights for bedroom where the lights are all automatic.
However in living room, I have three lights but I only want the fireplace light to be automatic.  I cannot seem to be able to specify that, with or without the `disable_entity:`

configuration.yaml without my #commented entries:
```
magic_areas:
  bedroom:
    presence_sensor_device_class: ['motion']
    automatic_lights:
      disable_entity: input_boolean.sleep_mode

  office:
    presence_sensor_device_class: ['motion']

  living_room:
    automatic_lights:
      - light.fireplace_light
    disable_entity: 'input_boolean.sleep_mode'
```

**Comment by danielbrunt57** [comment]
One issue I see is my living room lights: fireplace (Insteon), table lamp (Insteon) and pole lamp (Z-Wave) are all switches.  
I've added:
```
light:
  - platform: switch
    name: Pole Lamp
    entity_id: switch.appliance_module_zl7201us_switch
    
  - platform: switch
    name: Fireplace Light
    entity_id: switch.switchlinc_relay_dual_band_1f_b7_25
    
  - platform: switch
    name: Living Room Light
    entity_id: switch.switchlinc_relay_dual_band_1f_b3_c5

  - platform: switch
    name: Garage Light
    entity_id: switch.switchlinc_relay_dual_band_1f_b5_4a
```
but the integration listed for the new light.xxx entities is still `switch` and MA does not list any lights..
```
presence_sensors: media_player.lg_sj8, media_player.echo_dot_living_room, media_player.fire_tv, media_player.living_room, binary_sensor.lumi_lumi_sensor_motion_aq2_68988604_occupancy, binary_sensor.lumi_sensor_motion_living_room, switch.area_presence_hold_living_room
active_sensors: binary_sensor.lumi_lumi_sensor_motion_aq2_68988604_occupancy
lights: 
climate: climate.living_room
clear_timeout: 60
update_interval: 15
on_states: on, home, playing, open
exterior: false
automatic_lights: enabled
friendly_name: Area (Living Room)
icon: mdi:texture-box
device_class: occupancy
```
Same issue for Garage Light... it is an Insteon wall switch.

**Comment by danielbrunt57** [comment]
Finally figured out thanks partly to [https://synapselabs.io/posts/bring-home-assistant-area-to-life-with-magic-areas/](url)
````
magic_areas:

  bathroom:
    presence_sensor_device_class: ['motion']

  bedroom:
    presence_sensor_device_class: ['motion']
    automatic_lights:
      disable_entity: input_boolean.sleep_mode

  living_room:
    icon: 'hass:sofa'
    presence_sensor_device_class: ['motion']
    automatic_lights:
      entities: 
       - light.fireplace_light
      disable_entity: binary_sensor.south_patio_lux_override
    include_entities:
      - binary_sensor.lumi_sensor_motion_living_room
      - light.fireplace_light
      - light.pole_lamp
      - light.living_room_light
      - media_player.living_room_tv
```
