### ISSUE TITLE
Entity ID is not a string:

### ISSUE THREAD

**Issue by Anian-igor** [jseidl/hass-magic_areas#89]
Hello.
version 2.0.3
I got an warning in a log
`2021-02-01 13:02:14 WARNING (MainThread) [custom_components.magic_areas.base] Entity ID is not a string: ['light.yee1', 'light.yee2', 'light.yee3']`

Light.yee1, yee2, and yee3 located in room. But excluded
```
"exclude_entities": [
    "light.yee1",
    "light.yee2",
    "light.yee3"
],
```
I tried to remove from excluded list but nothing changed.

**Comment by danielbrunt57** [comment]
I too am seeing this new warning entry in my log:
```
 Logger: custom_components.magic_areas.base
Source: custom_components/magic_areas/base.py:531
Integration: Magic Areas (documentation, issues)
First occurred: 10:23:27 AM (4 occurrences)
Last logged: 10:23:27 AM
Entity ID is not a string: ['light.bathroom_light']
```
That is the only light in my bathroom and it's working correctly in MagicAreas...

**Comment by jseidl** [comment]
Currently investigating this

**Comment by danielbrunt57** [comment]
Here is the info from core.entity_registry for my one light that's triggering the warnings:
```
            {
                "entity_id": "light.bathroom_light",
                "config_entry_id": "00e6676b127211ebbf064df322fac86e",
                "device_id": "9ffc5618d5df2d3a408bae4f98c2d2c4",
                "area_id": null,
                "unique_id": "315e09",
                "platform": "insteon",
                "name": "Bathroom Light",
                "icon": "mdi:car-parking-lights",
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 1,
                "device_class": null,
                "unit_of_measurement": null,
                "original_name": "SwitchLinc Dimmer 31.5E.09",
                "original_icon": null
            },
```

I noticed area_id is null so I updated the area for it:
```
            {
                "entity_id": "light.bathroom_light",
                "config_entry_id": "00e6676b127211ebbf064df322fac86e",
                "device_id": "9ffc5618d5df2d3a408bae4f98c2d2c4",
                "area_id": "bathroom",
                "unique_id": "315e09",
                "platform": "insteon",
                "name": "Bathroom Light",
                "icon": "mdi:car-parking-lights",
                "disabled_by": null,
                "capabilities": {},
                "supported_features": 1,
                "device_class": null,
                "unit_of_measurement": null,
                "original_name": "SwitchLinc Dimmer 31.5E.09",
                "original_icon": null
            },
```
then restarted HA but the 4 warnings still persist...

**Comment by jseidl** [comment]
Looks like somewhere this list gets passed as the `entity_id`, still trying to track it down. Head scratcher...

**Comment by danielbrunt57** [comment]
I really don't know python but is it possible to determine and log what **type** it sees the object as?

**Comment by danielbrunt57** [comment]
I made a stab at it...
```
                        if not isinstance(entity["entity_id"], str):
                            _LOGGER.warning(f"Entity ID is not a string: {entity['entity_id']}")
                            _LOGGER.warning(f"Entity TYPE is: %s", type(entity['entity_id']))
```
```
Logger: custom_components.magic_areas.base
Source: custom_components/magic_areas/base.py:532
Integration: Magic Areas (documentation, issues)
First occurred: 5:36:57 AM (4 occurrences)
Last logged: 5:36:57 AM
Entity TYPE is: <class 'list'> 
```
This entity is an Insteon dimmer (I only have one) which is added to HA as a light.
My zigbee lights are okay.
I have other non-light switches (2 zwave and three insteon) that I've created templated light entities for and they are fine.
```
  - platform: template
    lights:
      pole_lamp:
        friendly_name: "Pole Lamp"
        unique_id: zwave-pole-lamp
        icon_template: >-
         hass:floor-lamp
        level_template: >-
          {% if is_state('switch.appliance_module_zl7201us_switch','on') %}255{% else %}0{% endif %}
        value_template: >-
          {{ is_state('switch.appliance_module_zl7201us_switch','on') }}
        turn_on:
          service: switch.turn_on
          entity_id: switch.appliance_module_zl7201us_switch
        turn_off:
          service: switch.turn_off
          entity_id: switch.appliance_module_zl7201us_switch
        set_level:
          service_template: >-
            {% if brightness > 0 %}switch.turn_on{% else %}switch.turn_off{% endif %}
          data:
            entity_id: switch.appliance_module_zl7201us_switch

      fireplace_light:
        friendly_name: "Fireplace Light"
        unique_id: insteon-fireplace-light
        icon_template: >-
         hass:spotlight-beam
        level_template: >-
          {% if is_state('switch.switchlinc_relay_dual_band_1f_b7_25','on') %}255{% else %}0{% endif %}
        value_template: >-
          {{ is_state('switch.switchlinc_relay_dual_band_1f_b7_25','on') }}
        turn_on:
          service: switch.turn_on
          entity_id: switch.switchlinc_relay_dual_band_1f_b7_25
        turn_off:
          service: switch.turn_off
          entity_id: switch.switchlinc_relay_dual_band_1f_b7_25
        set_level:
          service_template: >-
            {% if brightness > 0 %}switch.turn_on{% else %}switch.turn_off{% endif %}
          data:
            entity_id: switch.switchlinc_relay_dual_band_1f_b7_25
etc.
```
